version: "3.7"
services:
  server:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: ./docker/server/Dockerfile
    image: server
    container_name: server-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./server:/var/www
    networks:
      - network-server

  db:
    image: postgres:15.3
    container_name: server-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - network-server
#    ports:
#      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: server-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - network-server

networks:
  network-server:
    driver: bridge
